# print("2*2")
# print("Hello")
# print("besh kupaygan ikkiga,5*2")
# print("""nuriddin madiyev toshkent ahbarot texnalogiyalari uneversiteti talabasi""")
# print('a' ,'b' ,'c',)
# print('a','b','c',sep='*')
# print('d', 'e', 'k',sep='**')
# print('a','b','c',end='@')
# print('d','e','f',end='@@')
# print()
